from app.database import SessionLocal, Base, engine
from app.models import Company

Base.metadata.create_all(bind=engine)

db = SessionLocal()

companies = [
    Company(
        name="Rockstar Games",
        country="USA",
        city="New York",
        platform="PC/Console",
        engine="RAGE",
        careers_url="https://www.rockstargames.com/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="ArenaNet",
        country="USA",
        city="Bellevue",
        platform="PC",
        engine="Proprietary",
        careers_url="https://www.arena.net/en/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Moon Active",
        country="Israel",
        city="Tel Aviv",
        platform="Mobile",
        engine="Unity",
        careers_url="https://careers.moonactive.com",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Naughty Dog",
        country="USA",
        city="Santa Monica",
        platform="PC/Console",
        engine="Proprietary",
        careers_url="https://www.naughtydog.com/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="Insomniac Games",
        country="USA",
        city="Burbank",
        platform="PC/Console",
        engine="Proprietary",
        careers_url="https://www.insomniac.games/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="Zynga",
        country="USA",
        city="San Francisco",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://www.zynga.com/careers/",
        remote=True,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Scopely",
        country="USA",
        city="Culver City",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://www.scopely.com/careers/",
        remote=True,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Playtika",
        country="Israel",
        city="Herzliya",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://www.playtika.com/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="SuperPlay",
        country="Israel",
        city="Tel Aviv",
        platform="Mobile",
        engine="Unity",
        careers_url="https://www.superplay.co/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Plarium",
        country="Israel",
        city="Herzliya",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://plarium.com/en/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="CD Projekt Red",
        country="Poland",
        city="Warsaw",
        platform="PC/Console",
        engine="REDengine",
        careers_url="https://www.cdprojektred.com/en/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Larian Studios",
        country="Belgium",
        city="Ghent",
        platform="PC",
        engine="Divinity Engine",
        careers_url="https://larian.com/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Ubisoft",
        country="France",
        city="Paris",
        platform="PC/Console",
        engine="Anvil",
        careers_url="https://www.ubisoft.com/en-us/company/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="King",
        country="Sweden",
        city="Stockholm",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://www.king.com/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Remedy Entertainment",
        country="Finland",
        city="Espoo",
        platform="PC/Console",
        engine="Northlight",
        careers_url="https://www.remedygames.com/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Supercell",
        country="Finland",
        city="Helsinki",
        platform="Mobile",
        engine="Proprietary",
        careers_url="https://supercell.com/en/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
]

for company in companies:
    exists = db.query(Company).filter(Company.name == company.name).first()
    if not exists:
        db.add(company)

db.commit()

db.close()

print("Seed completed")