from app.database import SessionLocal, Base, engine
from app.models import Company, Job

Base.metadata.create_all(bind=engine)

db = SessionLocal()

companies = [
    Company(
        name="Rockstar Games",
        industry="Gaming",
        country="USA",
        city="New York",
        platform="PC/Console",
        engine="RAGE",
        website="https://www.rockstargames.com",
        careers_url="https://www.rockstargames.com/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="ArenaNet",
        industry="Gaming",
        country="USA",
        city="Bellevue",
        platform="PC",
        engine="Proprietary",
        website="https://www.arena.net",
        careers_url="https://www.arena.net/en/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Moon Active",
        industry="Gaming",
        country="Israel",
        city="Tel Aviv",
        platform="Mobile",
        engine="Unity",
        website="https://www.moonactive.com",
        careers_url="https://www.moonactive.com/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Naughty Dog",
        industry="Gaming",
        country="USA",
        city="Santa Monica",
        platform="PC/Console",
        engine="Proprietary",
        website="https://www.naughtydog.com",
        careers_url="https://www.naughtydog.com/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="Insomniac Games",
        industry="Gaming",
        country="USA",
        city="Burbank",
        platform="PC/Console",
        engine="Proprietary",
        website="https://www.insomniac.games",
        careers_url="https://www.insomniac.games/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=False,
    ),
    Company(
        name="Zynga",
        industry="Gaming",
        country="USA",
        city="San Francisco",
        platform="Mobile",
        engine="Proprietary",
        website="https://www.zynga.com",
        careers_url="https://www.zynga.com/careers/",
        remote=True,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Scopely",
        industry="Gaming",
        country="USA",
        city="Culver City",
        platform="Mobile",
        engine="Proprietary",
        website="https://www.scopely.com",
        careers_url="https://www.scopely.com/careers/",
        remote=True,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Playtika",
        industry="Gaming",
        country="Israel",
        city="Herzliya",
        platform="Mobile",
        engine="Proprietary",
        website="https://www.playtika.com",
        careers_url="https://www.playtika.com/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="SuperPlay",
        industry="Gaming",
        country="Israel",
        city="Tel Aviv",
        platform="Mobile",
        engine="Unity",
        website="https://www.superplay.co",
        careers_url="https://www.superplay.co/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Plarium",
        industry="Gaming",
        country="Israel",
        city="Herzliya",
        platform="Mobile",
        engine="Proprietary",
        website="https://plarium.com",
        careers_url="https://plarium.com/en/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=False,
        visa=False,
    ),
    Company(
        name="CD Projekt Red",
        industry="Gaming",
        country="Poland",
        city="Warsaw",
        platform="PC/Console",
        engine="REDengine",
        website="https://www.cdprojektred.com",
        careers_url="https://www.cdprojektred.com/en/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Larian Studios",
        industry="Gaming",
        country="Belgium",
        city="Ghent",
        platform="PC",
        engine="Divinity Engine",
        website="https://larian.com",
        careers_url="https://larian.com/jobs",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Ubisoft",
        industry="Gaming",
        country="France",
        city="Paris",
        platform="PC/Console",
        engine="Anvil",
        website="https://www.ubisoft.com",
        careers_url="https://www.ubisoft.com/en-us/company/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="King",
        industry="Gaming",
        country="Sweden",
        city="Stockholm",
        platform="Mobile",
        engine="Proprietary",
        website="https://www.king.com",
        careers_url="https://www.king.com/careers",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Remedy Entertainment",
        industry="Gaming",
        country="Finland",
        city="Espoo",
        platform="PC/Console",
        engine="Northlight",
        website="https://www.remedygames.com",
        careers_url="https://www.remedygames.com/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    Company(
        name="Supercell",
        industry="Gaming",
        country="Finland",
        city="Helsinki",
        platform="Mobile",
        engine="Proprietary",
        website="https://supercell.com",
        careers_url="https://supercell.com/en/careers/",
        remote=False,
        hybrid=True,
        onsite=True,
        relocation=True,
        visa=True,
    ),
    # --- Batch 1 expansion: 15 additional real, verified companies ---
    # Gaming
    Company(
        name="Bungie",
        industry="Gaming",
        country="USA",
        city="Bellevue",
        platform="PC/Console",
        website="https://www.bungie.net",
        careers_url="https://careers.bungie.com/jobs",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Blizzard Entertainment",
        industry="Gaming",
        country="USA",
        city="Irvine",
        platform="PC/Console",
        website="https://www.blizzard.com",
        careers_url="https://careers.blizzard.com/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Riot Games",
        industry="Gaming",
        country="USA",
        city="Los Angeles",
        platform="PC/Console",
        website="https://www.riotgames.com",
        careers_url="https://www.riotgames.com/en/work-with-us/jobs",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Electronic Arts",
        industry="Gaming",
        country="USA",
        city="Redwood City",
        platform="PC/Console",
        website="https://www.ea.com",
        careers_url="https://www.ea.com/careers",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Bethesda Game Studios",
        industry="Gaming",
        country="USA",
        city="Rockville",
        platform="PC/Console",
        website="https://bethesdagamestudios.com",
        careers_url="https://jobs.zenimax.com/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="FromSoftware",
        industry="Gaming",
        country="Japan",
        city="Tokyo",
        platform="PC/Console",
        website="https://www.fromsoftware.jp",
        careers_url="https://careers.fromsoftware.jp/en/index.html",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Team17",
        industry="Gaming",
        country="United Kingdom",
        city="Wakefield",
        platform="PC/Console",
        website="https://www.team17.com",
        careers_url="https://www.team17.com/careers/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="HoYoverse",
        industry="Gaming",
        country="China",
        city="Shanghai",
        platform="PC/Mobile",
        website="https://www.hoyoverse.com",
        careers_url="https://www.hoyoverse.com/en-us/careers",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Krafton",
        industry="Gaming",
        country="South Korea",
        city="Seongnam",
        platform="PC/Console/Mobile",
        website="https://www.krafton.com",
        careers_url="https://www.krafton.com/en/careers/jobs/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Niantic",
        industry="Gaming",
        country="USA",
        city="San Francisco",
        platform="Mobile",
        website="https://www.nianticlabs.com",
        careers_url="https://nianticlabs.com/careers/openings",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    # Israel Simulation & Training
    Company(
        name="Elbit Systems",
        industry="Simulation & Training",
        country="Israel",
        city="Haifa",
        platform="Simulation",
        website="https://elbitsystems.com",
        careers_url="https://elbitsystems.com/careers/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Israel Aerospace Industries",
        industry="Simulation & Training",
        country="Israel",
        city="Lod",
        platform="Simulation",
        website="https://www.iai.co.il",
        careers_url="https://jobs.iai.co.il/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Rafael Advanced Defense Systems",
        industry="Simulation & Training",
        country="Israel",
        city="Haifa",
        platform="Simulation",
        website="https://www.rafael.co.il",
        careers_url="https://career.rafael.co.il/",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Simigon",
        industry="Simulation & Training",
        country="Israel",
        city="Herzliya",
        platform="Simulation",
        website="https://www.simigon.com",
        careers_url="https://www.simigon.com/careers",
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
    Company(
        name="Simlat",
        industry="Simulation & Training",
        country="Israel",
        city="Petach Tikva",
        platform="Simulation",
        website="https://www.simlat.com",
        careers_url=None,
        remote=False,
        hybrid=False,
        onsite=False,
        relocation=False,
        visa=False,
    ),
]

for company in companies:
    exists = db.query(Company).filter(Company.name == company.name).first()
    if not exists:
        db.add(company)

db.commit()

# Verified, official job postings confirmed by URL. Do not add entries here
# without a real, confirmed official company job URL.
jobs = [
    dict(
        company_name="Rockstar Games",
        title="Senior Gameplay Programmer",
        city="Rockstar Australia",
        official_url="https://www.rockstargames.com/careers/openings/position/7695704003",
    ),
    dict(
        company_name="ArenaNet",
        title="Senior Technical Artist (Contract)",
        city=None,
        official_url="https://www.arena.net/en/careers/job/43f64bf5-7dea-4df9-8ff2-ce61477be705",
    ),
]

for job in jobs:
    company = db.query(Company).filter(Company.name == job["company_name"]).first()
    if not company:
        continue

    existing = (
        db.query(Job)
        .filter(Job.company_id == company.id, Job.official_url == job["official_url"])
        .first()
    )

    if existing:
        existing.title = job["title"]
        existing.city = job["city"]
        existing.platform = company.platform
        existing.status = "open"
        existing.source_type = "official"
        existing.is_verified = True
    else:
        db.add(
            Job(
                company_id=company.id,
                title=job["title"],
                department=None,
                country=None,
                city=job["city"],
                work_model=None,
                experience_level=None,
                platform=company.platform,
                official_url=job["official_url"],
                status="open",
                posted_date=None,
                first_seen=None,
                last_checked=None,
                notes=None,
                source_type="official",
                is_verified=True,
            )
        )

db.commit()
db.close()

print("Seed completed")